apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-control-plane-observability.fullname" . }}-grafana-admin
  labels:
    {{- include "notification-control-plane-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
