apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-control-plane-observability.fullname" . }}-kafka-exporter
  namespace: {{ .Values.exportersNamespace }}
  labels:
    {{- include "notification-control-plane-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-exporter
spec:
  type: ClusterIP
  selector:
    {{- include "notification-control-plane-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-exporter
  ports:
    - name: http
      port: {{ .Values.kafkaExporter.service.port }}
      targetPort: http
