apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "notification-control-plane-observability.fullname" . }}-prometheus
  labels:
    {{- include "notification-control-plane-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "notification-control-plane-observability.fullname" . }}-prometheus
roleRef:
  kind: Role
  name: {{ include "notification-control-plane-observability.fullname" . }}-prometheus
  apiGroup: rbac.authorization.k8s.io
