apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-control-plane-observability.fullname" . }}-prometheus-config
  labels:
    {{- include "notification-control-plane-observability.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval | quote }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval | quote }}

    rule_files:
      - /etc/prometheus/rules/*.yml

    scrape_configs:
      - job_name: notification-control-plane
        metrics_path: /metrics
        static_configs:
          - targets:
              - {{ printf "%s-api.%s.svc.cluster.local:8080" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-worker.%s.svc.cluster.local:8081" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-callback-gateway.%s.svc.cluster.local:8082" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-connector-email.%s.svc.cluster.local:8091" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-connector-sms.%s.svc.cluster.local:8092" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-connector-webhook.%s.svc.cluster.local:8093" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-connector-push.%s.svc.cluster.local:8094" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-connector-whatsapp.%s.svc.cluster.local:8095" .Values.appReleaseName .Values.appNamespace | quote }}
              - {{ printf "%s-postgres-exporter.%s.svc.cluster.local:%d" (include "notification-control-plane-observability.fullname" .) .Values.exportersNamespace (int .Values.postgresExporter.service.port) | quote }}
              - {{ printf "%s-kafka-exporter.%s.svc.cluster.local:%d" (include "notification-control-plane-observability.fullname" .) .Values.exportersNamespace (int .Values.kafkaExporter.service.port) | quote }}
{{- range .Values.prometheus.extraTargets }}
              - {{ . | quote }}
{{- end }}

      - job_name: cadvisor
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - {{ .Release.Namespace | quote }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
            action: keep
            regex: cadvisor
          - source_labels: [__meta_kubernetes_pod_phase]
            action: keep
            regex: Running
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            regex: (.+)
            replacement: $1:{{ .Values.cadvisor.service.port }}
