apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notification-control-plane-observability.fullname" . }}-prometheus
  labels:
    {{- include "notification-control-plane-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
