apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-control-plane.componentName" (list . "callback-gateway") }}
  labels:
    {{- include "notification-control-plane.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "notification-control-plane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: callback-gateway
  ports:
    - name: http
      port: 8082
      targetPort: http
